networks:
  localtest:
    external: true

volumes:
  localtest_certs:
    external: true

services:
  nodejs:
    image: node:20-alpine
    networks:
      localtest:
    working_dir: /app
    volumes:
      - ./src:/app:ro
      - /app/node_modules
    command:
      - /bin/sh
      - -ec
      - |
        # deps
        npm ci
        # run
        node sample_app.js
    labels:
      traefik.enable: true
      traefik.http.routers.examples_nodejs.rule: Host(`nodejs.examples.test`)
      traefik.http.routers.examples_nodejs.entrypoints: https
      traefik.http.routers.examples_nodejs.service: examples_nodejs
      traefik.http.services.examples_nodejs.loadbalancer.server.port: 8080

  nodejs_ca:
    image: node:20-alpine
    networks:
      localtest:
    working_dir: /app
    volumes:
      - localtest_certs:/certs:ro
      - ./src:/app:ro
      - /app/node_modules
    environment:
      NODE_EXTRA_CA_CERTS: /certs/ca-bundle.pem
    command:
      - /bin/sh
      - -ec
      - |
        # deps
        npm ci
        # run
        node sample_app.js
    labels:
      traefik.enable: true
      traefik.http.routers.examples_nodejs_ca.rule: Host(`nodejs-ca.examples.test`)
      traefik.http.routers.examples_nodejs_ca.entrypoints: https
      traefik.http.routers.examples_nodejs_ca.service: examples_nodejs_ca
      traefik.http.services.examples_nodejs_ca.loadbalancer.server.port: 8080
