networks:
  localtest:
    external: true

volumes:
  localtest_certs:
    external: true

services:
  java:
    image: openjdk:21-jdk-slim
    networks:
      localtest:
    working_dir: /app
    volumes:
      - ./src:/app:ro
    command:
      - /bin/sh
      - -ec
      - |
        # compile
        javac SampleApp.java -d /tmp
        # run
        java -cp /tmp SampleApp
    labels:
      traefik.enable: true
      traefik.http.routers.examples_java.rule: Host(`java.examples.test`)
      traefik.http.routers.examples_java.entrypoints: https
      traefik.http.routers.examples_java.service: examples_java
      traefik.http.services.examples_java.loadbalancer.server.port: 8080

  java_ca:
    image: openjdk:21-jdk-slim
    networks:
      localtest:
    working_dir: /app
    volumes:
      - localtest_certs:/certs:ro
      - ./src:/app:ro
    command:
      - /bin/sh
      - -ec
      - |
        set -x

        # convert custom CA root to p12
        keytool -importcert \
          -file /certs/ca-localtest.pem \
          -keystore /tmp/truststore.p12 \
          -storepass truststore \
          -alias ca-localtest \
          -noprompt

        keytool -list \
          -keystore /tmp/truststore.p12 \
          -storepass truststore

        # compile
        javac SampleApp.java -d /tmp

        # run
        java -cp /tmp \
          -Djavax.net.ssl.trustStore=/tmp/truststore.p12 \
          -Djavax.net.ssl.trustStorePassword=truststore \
          -Djdk.tls.client.protocols=TLSv1.2 \
          SampleApp
    labels:
      traefik.enable: true
      traefik.http.routers.examples_java_ca.rule: Host(`java-ca.examples.test`)
      traefik.http.routers.examples_java_ca.entrypoints: https
      traefik.http.routers.examples_java_ca.service: examples_java_ca
      traefik.http.services.examples_java_ca.loadbalancer.server.port: 8080
