global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

accesslog: {}

ping: true

api:
  dashboard: true
  disabledashboardad: true

entryPoints:
  https:
    address: ":443"
    asDefault: true
    http:
      tls: {}
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: proxy
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

tls:
  certificates:
    - certFile: /etc/traefik/certs/proxy.crt
      keyFile: /etc/traefik/certs/proxy.key
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
